### PR TITLE
[Feature] send user's groups to clients

### PR DESCRIPTION
**Pull request by ralequi**
This feature transfers group names (not priviledges) to clients.

This PR is built on top of #61 & #62

### CODE REVIEW

**Comment by GaretJax** [comment]
Thanks for the PR @ralequi.

We have been discussing this with the team and, as this package is being used internally in code paths in our products that we are looking into deprecating, we will stop maintaining this package. We will thus not have the bandwidth necessary to ensure a thorough security process, as required for such a delicate package.

May I suggest that you fork the package instead? Is there any drawback apart from the obvious PyPI name clash?

**Comment by ralequi** [comment]
hi @GaretJax , it's ok to fork it. In fact, we've already "unofficially" forked it on https://github.com/naudit/django-simple-sso and https://pypi.org/project/django-simple-sso.naudit/
I made them to simplify our workflow until you merge (or not) my PRs.
However, as far as we are integrating the simple-SSO into our login system, I have no problem on become an official maintainer.

If you are planning to drop/deprecate the project, I'll like to get access to the official pypi repository, so I can keep it updated without being an "unofficial fork". If not, well, of course I'll keep my fork but would have much less impact on the community probably.

We can keep talking on email if you prefer or on this thread, but as I said, I'm open to keep the project alive (I need to BTW)

**Comment by GaretJax** [comment]
Thank you for your understanding @ralequi.

We plan to stop maintaining the project, but we're not yet ready to give up ownership, as the supply-chain issues that we would encounter are the same as continuing to integrate changes without sufficient review. We are open to discuss this again in the future once we transition our solution to OAuth/OpenID.

**Comment by ralequi** [comment]
Nice.
In any case, we are going to keep maintaining the fork. Probably now with more emphasis as it may become the main project someday. 
Let's keep in touch and I'm open to help on this project, so feel free to ask for it. (nevertheless i'm on vacation this month)

**Comment by GaretJax** [comment]
Thank you, and enjoy your vacation!

**Pull request closed without merging**
